etcd:
  host: 192.168.1.38
  port: 2379

db:
  user: root
  password: Forever634312.
  host: 192.168.0.200
  port: 3306
  defaultDatabase: server
  dns: ?charset=utf8&parseTime=true&loc=Local

redis:
  host: 192.168.0.200
  port: 6379
  user:
  password:
  db: 1

rabbitmq:
  user: admin
  password: admin
  host: 192.168.0.200
  port: 5672

logredis:
  host: 192.168.0.200
  port: 6379
  password:
  db: 15
  key: logs