// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cleanup

// Injectors from wire.go:

func New() (*Mission, func(), error) {
	player, cleanup, err := NewPlayer()
	if err != nil {
		return nil, nil, err
	}
	monster, cleanup2, err := NewMonster()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mission, cleanup3, err := NewMission(player, monster)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return mission, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
