// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *Service {
	clusterClient := NewRedis()
	db := NewMysql()
	service := &Service{
		Redis: clusterClient,
		DB:    db,
	}
	return service
}

// wire.go:

var utils = wire.NewSet(NewRedis, NewMysql)
