// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sets

// Injectors from wire.go:

func NewServiceCA() (*ServiceC, func(), error) {
	conf := NewConf()
	serviceC, cleanup, err := NewServiceC(conf)
	if err != nil {
		return nil, nil, err
	}
	return serviceC, func() {
		cleanup()
	}, nil
}
